# Generated by Django 4.1.5 on 2023-01-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
